spring:
  redis:
    host: ENC(2yxDyA11oEJint+3xS3JlGYgJxuNySAsGlhSd/EaVb4TG/MlFE9adgHuj3nxqQDFrO0doRG7E7zevWYFI8rj/pimwQxlelXDBe1QtMo7Ir7d1aBsEdbQwAPfHLHUgKVO)
    #    host: 127.0.0.1
    port: 6379
